GTNewHorizons/EnderIO

src/main/java/crazypants/enderio/item/KeyTracker.java
src/main/java/crazypants/enderio/item/darksteel/DarkSteelController.java

Allow to use EnderIO NightVision hotkey for switch Thaumic Exploration NightVision helm enchant.

Added support for NightVision enchant

---

src/main/java/crazypants/enderio/enchantment/EnchantmentSoulBound.java

Reverts GTNewHorizons/EnderIO#4

Revert "Allow Galacticraft handles SoulBound itself"

---

src/main/java/crazypants/enderio/nei/NEIEnderIOConfig.java

See GTNewHorizons/GT-New-Horizons-Modpack#4928

Hide tile.blockLightNode.name in NEI

---

gradle.properties
src/main/java/crazypants/enderio/machine/farm/FarmersRegistry.java
src/main/java/crazypants/enderio/machine/farm/farmers/ForestryFarmer.java

Cherry picked & backported from 1b242dc2d786b8c1fb545845768faa1f6c15818a

Added forestry sapling support to farm station

---

src/main/java/crazypants/enderio/conduit/ConduitUtil.java

* Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9236

Fix error migrating advanced ender fluid conduits

---

src/main/java/crazypants/enderio/config/Config.java
src/main/java/crazypants/enderio/machine/obelisk/attractor/TileAttractor.java
src/main/java/crazypants/enderio/machine/obelisk/aversion/TileAversionObelisk.java
src/main/java/crazypants/enderio/machine/slicensplice/TileSliceAndSplice.java
src/main/java/crazypants/enderio/machine/soul/TileSoulBinder.java
src/main/java/crazypants/enderio/machine/spawner/TilePoweredSpawner.java

fix new capacitor behave in some machine

EIO capacitor fix

---

src/main/java/crazypants/enderio/teleport/TravelController.java

Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8881

Fix chat spam when try to blink but staff does not have enough power

---

src/main/java/crazypants/enderio/xp/ExperienceContainer.java

Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8144

Fix overflow with XP container machines

---

src/main/java/crazypants/enderio/config/Config.java
src/main/java/crazypants/enderio/teleport/TravelController.java

I'm not sure if this is 100% fine, so added config to disable this feature.
https://user-images.githubusercontent.com/40035906/164971847-abbbedbb-cf56-4f7f-a148-1116b1ab8abe.mp4

Allow blinking onto the roof

---

src/main/java/crazypants/enderio/machine/spawner/TilePoweredSpawner.java

GTNewHorizons/GT-New-Horizons-Modpack#10084

Fix powered spawner wrong behavior

---

build.gradle
dependencies.gradle
gradle.properties
src/main/java/crazypants/enderio/EnderIO.java

This avoids saving an empty file in case of a crash during load

Save ServerChannelRegister on every world save, and avoid saving corrupted data on server crashes.

---

src/main/java/crazypants/enderio/conduit/gui/BaseSettingsPanel.java
src/main/java/crazypants/enderio/conduit/gui/ExternalConnectionContainer.java
src/main/java/crazypants/enderio/conduit/gui/GuiExternalConnection.java
src/main/java/crazypants/enderio/conduit/gui/LiquidSettings.java
src/main/java/crazypants/enderio/conduit/gui/item/BasicItemFilterGui.java
src/main/java/crazypants/enderio/conduit/gui/item/BigItemFilterGui.java
src/main/java/crazypants/enderio/conduit/gui/item/ExistingItemFilterGui.java
src/main/java/crazypants/enderio/conduit/gui/item/ModItemFilterGui.java
src/main/java/crazypants/enderio/conduit/gui/item/PowerItemFilterGui.java

Fixes <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10567>
Fixes <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10570>

Conduit gui fixes

---

src/main/java/crazypants/enderio/machine/obelisk/weather/EntityWeatherRocket.java

This also fixes GTNewHorizons/GT-New-Horizons-Modpack#10758

Fix weather obelisk not working anywhere but overworld

---

src/main/java/crazypants/enderio/api/teleport/TravelSource.java

Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10913

Fix teleport server error

---

.gitattributes
build.gradle
src/main/java/crazypants/enderio/conduit/BlockConduitBundle.java

Remove null checks that are already covered by instanceof
Fixes <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11474>

Guard against ClassCastExceptions in BlockConduitBundle

---

build.gradle
dependencies.gradle
gradle.properties
src/main/java/crazypants/enderio/machine/farm/farmers/CustomSeedFarmer.java
src/main/java/crazypants/enderio/nei/SagMillRecipeHandler.java
src/main/java/crazypants/enderio/nei/VatRecipeHandler.java

Address part of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11516

Add Fertilized Dirt from RandomThings to recognized farmland list for CustomSeedFarmer

---

build.gradle
src/main/java/crazypants/enderio/nei/EnchanterRecipeHandler.java

Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12030

Fix behavior on Enchanter NEI while holding shift

---

.editorconfig
src/main/java/crazypants/enderio/conduit/gui/item/ItemSettings.java

Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12753
@eigenraven I'm not totally sure what you meant by superclass send a copy after all click in #101. Please help check I didn't break anything!

fix item conduit settings not sent to server

---

src/main/resources/assets/enderio/lang/de_DE.lang

More German Translation

---

src/main/java/crazypants/enderio/teleport/TravelController.java

Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13406

Fix crash with outOfRange on server

---

src/main/java/crazypants/enderio/conduit/power/endergy/PowerConduitEndergy.java

Most overwrites here are not needed imao. This file is nearly an exact copy of `PowerConduit`, but this is not needed as we already extend `PowerConduit`.

Cleanup PowerConduitEndergy

---

src/main/java/crazypants/enderio/api/teleport/IItemOfTravel.java
src/main/java/crazypants/enderio/config/Config.java
src/main/java/crazypants/enderio/item/darksteel/ItemDarkSteelPickaxe.java
src/main/java/crazypants/enderio/item/darksteel/ItemDarkSteelSword.java
src/main/java/crazypants/enderio/teleport/ItemTeleportStaff.java
src/main/java/crazypants/enderio/teleport/ItemTravelStaff.java
src/main/java/crazypants/enderio/teleport/TravelController.java
src/main/java/crazypants/enderio/teleport/packet/PacketLongDistanceTravelEvent.java
src/main/java/crazypants/enderio/teleport/packet/PacketTravelEvent.java

I'm not very familiar with telepad and advanced uses of travel anchors. Please help test this in game and review the code to ensure I didn't accidentally block legitimate tp attempts.

valiate tp packets

---

src/main/java/crazypants/enderio/item/darksteel/ItemDarkSteelPickaxe.java
src/main/java/crazypants/enderio/item/darksteel/ItemDarkSteelSword.java

fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14029

fix travel upgrade items using wrong way to determine power stored

---

build.gradle
dependencies.gradle
src/main/java/crazypants/enderio/teleport/TravelController.java
src/main/java/crazypants/enderio/teleport/packet/PacketTravelEvent.java

fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14456

allow small overshoot of power use for traveling 

---

dependencies.gradle
src/main/java/crazypants/enderio/conduit/BlockConduitBundle.java

closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14698

Open conduit connection GUI with more wrenches using shift + left-click

---

build.gradle
dependencies.gradle
settings.gradle
src/main/java/crazypants/enderio/EnderIO.java

Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15294 by making the dependency on cofhlib explicit.
There may be an argument (somewhere?) that it would be better to make the dependency soft by wrapping everything that uses it in a "ifModLoaded" but that's for others to consider.
Also updated the dependencies.gradle to match the dependencies in the mod itself.

add required hard dependency on cofhlib

---

src/main/java/crazypants/enderio/conduit/ConduitUtil.java
src/main/java/crazypants/enderio/conduit/render/ConduitBundleRenderer.java

Some null checks to avoid outright crashing with Angelica, 

---

dependencies.gradle
src/main/java/crazypants/enderio/machine/capbank/render/CapBankRenderer.java
src/main/java/crazypants/enderio/machine/capbank/render/FillGauge.java
src/main/java/crazypants/enderio/machine/capbank/render/IoDisplay.java

depends on https://github.com/GTNewHorizons/EnderCore/pull/21 to be tagged as 0.4.4

Reduce allocation spam in capacitor banks

---

src/main/java/crazypants/enderio/conduit/liquid/LiquidConduitRenderer.java

Maybe Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16363

Probably less thread unsafe.

---

src/main/java/crazypants/enderio/conduit/TileConduitBundle.java

* Not entirely sure why it's being concurrently modified.. so let's just make it safe for now
Maybe fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16586

Work around CME

---

src/main/java/crazypants/enderio/conduit/TileConduitBundle.java

Try a CasList, since the Collections.synchronizedList actually needed the reads to be synchronized...

Probably more threadsafe

---

src/main/java/crazypants/enderio/conduit/liquid/LiquidConduit.java

Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16756
See issue for details

Fix LiquidConduit not attempting to pull fluids from all directions if one of external tanks are empty

---

src/main/java/crazypants/enderio/conduit/me/ItemMEConduit.java

Closes [#17869](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17869)

removed conduit subtype

---

src/main/java/crazypants/enderio/machine/AbstractMachineEntity.java
src/main/java/crazypants/enderio/material/ItemCapacitor.java

Closes GTNewHorizons/GT-New-Horizons-Modpack#14881

Prevent Silver Capacitor from being used as Upgrade

---

src/main/java/crazypants/enderio/machine/generator/zombie/TileZombieGenerator.java

Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17254

Fix Zombie Generator NPE

---

src/main/java/crazypants/enderio/machine/light/BlockLightNode.java

Adds a small sanity check. The other part required to fix my issue explained here: https://github.com/GTNewHorizons/FloodLights/pull/8

ensure `TileLightNode` instance at `breakBlock`

---

src/main/java/crazypants/enderio/item/darksteel/upgrade/TrackmanGogglesUpgrade.java

I accidently copied the wrong config line form the naturalist armor

fix trackman's goggles config

---

dependencies.gradle
src/main/java/crazypants/enderio/item/darksteel/ItemEndSteelArmor.java
src/main/java/crazypants/enderio/item/darksteel/ItemStellarArmor.java

see https://github.com/GTNewHorizons/GT5-Unofficial/pull/4142

Move End Steel/ Stellar Armor to GT Hazard API

---

gradle.properties
src/main/java/crazypants/enderio/machine/alloy/GuiAlloySmelter.java
src/main/java/crazypants/enderio/machine/buffer/GuiBuffer.java
src/main/java/crazypants/enderio/machine/crafter/GuiCrafter.java
src/main/java/crazypants/enderio/machine/enchanter/GuiEnchanter.java
src/main/java/crazypants/enderio/machine/farm/GuiFarmStation.java
src/main/java/crazypants/enderio/machine/generator/combustion/GuiCombustionGenerator.java
src/main/java/crazypants/enderio/machine/generator/stirling/GuiStirlingGenerator.java
src/main/java/crazypants/enderio/machine/generator/zombie/GuiZombieGenerator.java
src/main/java/crazypants/enderio/machine/gui/GuiMachineBase.java
src/main/java/crazypants/enderio/machine/invpanel/GuiInventoryPanel.java
src/main/java/crazypants/enderio/machine/killera/GuiKillerJoe.java
src/main/java/crazypants/enderio/machine/obelisk/attractor/GuiAttractor.java
src/main/java/crazypants/enderio/machine/obelisk/aversion/GuiAversionObelisk.java
src/main/java/crazypants/enderio/machine/obelisk/weather/GuiWeatherObelisk.java
src/main/java/crazypants/enderio/machine/obelisk/xp/GuiExperienceObelisk.java
src/main/java/crazypants/enderio/machine/painter/GuiPainter.java
src/main/java/crazypants/enderio/machine/spawner/GuiPoweredSpawner.java
src/main/java/crazypants/enderio/machine/tank/GuiTank.java
src/main/java/crazypants/enderio/machine/transceiver/gui/GuiTransceiver.java
src/main/java/crazypants/enderio/nei/AlloySmelterRecipeHandler.java
src/main/java/crazypants/enderio/nei/EnchanterRecipeHandler.java
src/main/java/crazypants/enderio/nei/NEIEnderIOConfig.java
src/main/java/crazypants/enderio/nei/SagMillRecipeHandler.java
src/main/java/crazypants/enderio/nei/SliceAndSpliceRecipeHandler.java
src/main/java/crazypants/enderio/nei/SoulBinderRecipeHandler.java
src/main/java/crazypants/enderio/nei/VatRecipeHandler.java
src/main/resources/META-INF/enderio_at.cfg

| before | after |
|-|-|
| ![image](https://github.com/user-attachments/assets/5c638ecf-632b-4feb-afc7-b62da274e0ce) | ![image](https://github.com/user-attachments/assets/8396b49e-1886-465b-a5e4-5ceae51776c3) |
| before | after |
|-|-|
| ![image](https://github.com/user-attachments/assets/48ab17b1-3104-4062-b5ec-5299b129efec) | ![image](https://github.com/user-attachments/assets/8dd65f83-5cab-420c-b2d0-4b04907722a5) |
| before | after |
|-|-|
| ![image](https://github.com/user-attachments/assets/61dfe603-d5b0-4e4a-b40f-74873d23cfc2) | ![image](https://github.com/user-attachments/assets/1b46f024-9d0e-4334-a71d-a321dcffec47) |
| before | after |
|-|-|
| ![image](https://github.com/user-attachments/assets/89aadb8c-7dc4-4516-bb63-6ae772b18364) | …

Update NEI Handlers

---

src/main/java/crazypants/enderio/conduit/BlockConduitBundle.java

fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20569

fix NPE in BlockConduitBundle#onPlaySound

---

dependencies.gradle
src/main/java/crazypants/enderio/EnderIO.java
src/main/java/crazypants/enderio/machine/farm/farmers/PlantableFarmer.java

Prior to this the farming station could only harvest an already planted Pam's nether seed.
With this modification it is now possible for the farming station to plant the seeds as well.
Must be merged after GTNewHorizons/Hodgepodge/pull/637

Added the ability for the farming station to plant Pam's nether seeds
