GTNewHorizons/EnderIO

src/main/java/crazypants/enderio/item/ItemSoulVessel.java
See GTNewHorizons/GT-New-Horizons-Modpack#6867
If the client sends `C02PacketUseEntity` too quickly then `itemInteractionForEntity` can be called with a dead entity as argument. There is nothing in vanilla/forge code to stop this. 
Imagine 2 `C02PacketUseEntity` arrived at the server in the same tick. the first packet will grab the correct mob, set the dead flag and add a filled vial. The entity will then be scheduled for removal at next tick. However before that happens, the second packet will grab the same mob, set the dead flag again (without first checking if this entity is alive) and add another filled vial.
An ideal solution would be patch the `NetHandlerPlayServer::processUseEntity` with ASM, but that'd be a bit too tedious. This patch will simply add a `isDead` check to relevant …
=> Ignore dead entities when capturing mobs with soul vial

src/main/java/crazypants/enderio/conduit/BlockConduitBundle.java, src/main/java/crazypants/enderio/conduit/gui/LiquidSettings.java, src/main/java/crazypants/enderio/conduit/liquid/EnderLiquidConduit.java, src/main/java/crazypants/enderio/conduit/liquid/EnderLiquidConduitNetwork.java, src/main/java/crazypants/enderio/conduit/packet/PacketRoundRobinMode.java
GTNewHorizons/GT-New-Horizons-Modpack#7082
This will
1. Old ender conduit will by default have round robin on, to preserve original behavior
2. New ender conduits will by default have round robin off, as a best effort attempt to minimize lag
=> Add round-robin button to ender conduit

src/main/java/crazypants/enderio/conduit/BlockConduitBundle.java, src/main/java/crazypants/enderio/conduit/gui/LiquidSettings.java, src/main/java/crazypants/enderio/conduit/gui/PacketFluidChannel.java, src/main/java/crazypants/enderio/conduit/gui/item/ItemSettings.java, src/main/java/crazypants/enderio/conduit/liquid/EnderLiquidConduit.java, src/main/java/crazypants/enderio/conduit/liquid/EnderLiquidConduitNetwork.java, src/main/java/crazypants/enderio/conduit/liquid/EnderLiquidConduitRenderer.java
This is pretty basic support for channels on ender fluid conduits. It mainly copies item conduits for gui and rendering and does the most basic check possible to match source and target before checking target filters or target acceptance.
=> Initial support for channels on EnderFluidConduits

src/main/java/crazypants/enderio/gui/TooltipHandlerBurnTime.java
Revert 3093ea6180beec8329087a1f91bda448683331d8 which broke the "Burn Time:" tooltip.  Recent enhancements to `getBurnTime` in GT, and NEI caching it should improve the CPU usage.  If it remains a problem, a cache here would be a better idea.
=> Fix Burn Time tooltip

src/main/java/crazypants/enderio/machine/capbank/TileCapBank.java
type can be null in some conditions when it is accessed here, the getType() accessor should be used instead.
=> fix a crash with capacitor banks

build.gradle, gradle.properties, src/main/java/crazypants/enderio/conduit/liquid/AbstractEnderLiquidConduit.java, src/main/java/crazypants/enderio/conduit/liquid/AbstractTankConduit.java, src/main/java/crazypants/enderio/conduit/liquid/AdvancedLiquidConduit.java, src/main/java/crazypants/enderio/conduit/liquid/LiquidConduit.java
Consistently guard against the same input calling fill multiple times per tick across all fluid type conduits.  *cough* GT output hatch *cough*
=> Fill from sanity

src/main/java/crazypants/enderio/conduit/item/filter/ItemFilter.java
Partially address https://discord.com/channels/181078474394566657/522098956491030558/909118918705172530
There is no way to completely address this lag, as it's caused by the sheer amount of item being moved. You cannot "fix" that without kicking said player(s) out of game.
=> Optimize filter code

build.gradle, dependencies.gradle, src/main/java/crazypants/enderio/machine/farm/FarmersRegistry.java
Prevents MC from crashing with a ClassNotFoundException when Forestry is not installed
=> Make Forestry a soft-dependency

src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java
before, it was using meta id as a way to detect tiers. But because this was changed to check tier of the capacitor instead, it introduced a shift in the ranges, making the double-layer capacitor working as an octadict capacitor and so on. This PR fix the shift. There could be potential shifts like that somewhere in the mod, but couldn't bother to check.
=> fix farming station range

src/main/java/crazypants/enderio/conduit/gui/item/BigItemFilterGui.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10098
Rearranged buttons in Big Advanced Item Filter to make Ignore/Match Meta Data and Sticky Mode Enabled/Disabled buttons not overlap with each other.
Before:
After:
=> fix: moving around buttons in Big Advanced Item Filter

src/main/java/crazypants/enderio/api/teleport/TravelSource.java
This fixes GTNewHorizons/GT-New-Horizons-Modpack#10795 and Ender IO (The block) to work with custom travel block config option.
=> [FIX] Anchor distance config option not working

src/main/java/crazypants/util/IFacade.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10822
I'm not sure if this is the right way, but works for both when Chisel is loaded and not loaded.
=> Fix crash when Waila is loaded and Chisel is not loaded

src/main/java/crazypants/enderio/conduit/render/ConduitBundleRenderer.java, src/main/java/crazypants/enderio/machine/capbank/GuiCapBank.java, src/main/java/crazypants/enderio/machine/hypercube/GuiHyperCube.java, src/main/java/crazypants/enderio/machine/power/GuiCapacitorBank.java, src/main/java/crazypants/enderio/teleport/anchor/TravelEntitySpecialRenderer.java
I might not be a OpenGL expert, but I do know these calls are somewhat expensive and should not be called like that.
=> collapse continuous glPushAttrib into one call

src/main/java/crazypants/enderio/teleport/TravelController.java
Also fix the check so that we only display the message for travel anchors within the angle limit.
=> Add distance limit for out-of-range message

src/main/java/crazypants/enderio/teleport/TravelController.java
This bug does not currently have any gameplay effect, because the return value of this method is not used to determine teleport range. But we should fix it anyway.
=> Fix for `getTravelItemTravelSource`

src/main/java/crazypants/enderio/waila/WailaCompat.java
It's another item, that's why it's not shown. With this change, it shows the used/max energy now:
=> Fix Waila tooltip for Endergy Energy Conduits

src/main/java/crazypants/enderio/config/Config.java, src/main/java/crazypants/enderio/machine/solar/SolarPanelNetwork.java
While you can configure the max output RF of solar panals, it would be useful to configure the max storable energy aswell to scale it with the max output RF. This PR fixes it (tested).
Default value for all solar panels is 10000 RF (as before).
- Solar Panel
- Max Out: 100 RF
- Capacity: 10000 RF
- Advanced Solar Panel
- Max Out: 1000 RF
- Capacity: 100000 RF
- Vibrant Solar Panel
- Max Out: 10000 RF
- Capacity: 1000000 RF
As you can see, with 10000 RF output the max capacity of 10000 is a hard limit (in several aspects).
=> Solar Panels: Use config for capacity RF

src/main/java/crazypants/enderio/machine/solar/SolarPanelNetwork.java
It's not critical at all but I've found this little missing check after one of my previous PRs got merged.
**Before:** Error message in Server Console without any effect to the functionality at loading a solar panel's data.
**After:** No error message.
=> Fix NullReferenceException at getCapacity->getBlockMetadata

src/main/java/crazypants/enderio/machine/solar/SolarPanelNetwork.java
My previous PR #97 fixes a null reference exception but as side effect it prevents single solar cells to re-try to apply the correct config at a later time when they actually have a network. This PR corrects it, the solar cells are working 100%ly correct now.
=> Apply max capacity config also for single solar cells without network

src/main/java/crazypants/enderio/conduit/me/MEConduit.java
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12534
The `IGridNode.destory()` call is redundant here and absolutely not needed as it gets already destroyed on another location. It forces a validation of the GridNode that then adds itself to a new Grid (via AE2 itself) - on each onChunkUnload for each single conduit in a Grid of multiple GridNodes.
It took me a long time to find this out and  today I got it throw debugging and checking the stack trace.
*(Sorry, have no better pic made when I found it. I did this before to remember just for the case.)*
=> Fix ME Conduits onChunkUnload

src/main/java/crazypants/enderio/conduit/me/MEConduit.java
Reverts GTNewHorizons/EnderIO#107 as it only tooks only effect in my test worlds but not the productive world and even increase the lag a little bit. It seems to not directly fix the issue and I have no more time yet to investigate more troubleshooting.
Sorry for the probably too early PR...
=> Revert "Fix ME Conduits onChunkUnload"

src/main/java/crazypants/enderio/conduit/AbstractConduit.java, src/main/java/crazypants/enderio/conduit/me/MEConduit.java
Fixes a case where at loading the Grid sometimes the conduits may not connect.
I've tested this case with all conduit types and all me cables and some buses and mashines, still work as it should.
Before:
After:
=> Improve canConnectToExternal()

src/main/java/crazypants/enderio/conduit/AbstractConduit.java, src/main/java/crazypants/enderio/conduit/me/MEConduit.java
Adds comments to the method and field `AbstractConduit.needUpdateConnections` and also at the call at `MEConduit.canConnectToExternal`.
Squash and merge recommended (messed up the history in my master).
=> Add comments for `needUpdateConnections`

src/main/java/crazypants/enderio/conduit/AbstractConduit.java
After the latest commit yesterday we had massive lag spikes on your prod server, specifically when interacting with the ME . I was not able to detect with Opis, but this PR seems to fix the issue.
Basically this change doesn't affect the functionality but only allows a re-try while `updateConnections()` is executed and make the code looking minimal better.
@repo-alt @eigenraven (or anyone that knows the answer)
Can you ensure to 100% that a Part can NEVER live without a GridNode forever? Or could there be the case that a Part never gets a GridNode (for any reason)?
And also, how many ticks should it take maximal for the whole Grid and all Parts to initialize? Is that always done on one single tick or does it depend on the amount of Parts and Grid elements?
I need to know that because then …
=> `needUpdateConnections` only while updating cons

src/main/java/crazypants/enderio/item/ItemMagnet.java, src/main/java/crazypants/enderio/teleport/ItemTeleportStaff.java, src/main/java/crazypants/enderio/teleport/ItemTravelStaff.java
I think I've seen a few reports of the Ender IO staff of traveling and staff of teleportation somehow getting set to IIRC, near `Integer.MIN_VALUE` amount of stored energy. Reading through the code, the only way I could see for this to happen was if `receiveEnergy` or `extractEnergy` was called with a very negative number.
If I'm right about the cause, then this PR will fix the symptoms for Ender IO, but it won't fix the underlying issue that we have code somewhere which occasionally overflows and calls `receiveEnergy` or (less likely) `extractEnergy` with, I'm guessing, a value near `Integer.MIN_VALUE`, and any other mods that contain subclasses of `ItemEnergyContainer` may still be affected by the issue.
I don't know much about mix-ins, but we could also try putting these checks …
=> Try to fix energy overflow

src/main/java/crazypants/enderio/conduit/ConduitUtil.java, src/main/java/crazypants/enderio/conduit/me/MEConduit.java
Here the final fix for ME Conduits ghostloading. This time real, not sure how I didn't see this before, but thanks to repo-alt's change to AE2Stuff I had an idea for what I could search.
Is it ok to store the position + offset in variables? I don't like that long line twice. But just tell me. :)
Similar to https://github.com/GTNewHorizons/ae2stuff/pull/8
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12534
=> prevent ghostloading

src/main/java/crazypants/enderio/config/Config.java, src/main/java/crazypants/enderio/machine/transceiver/TileTransceiver.java
It's not possible to incrase the `transceiverMaxIoRF` over the hardcoded 500.000/2 RF for internal capacitor bank.
This PR changes this by making it configurable.
=> Use config for transceiver's energy buffer

src/main/java/crazypants/enderio/conduit/power/PowerConduit.java, src/main/java/crazypants/enderio/conduit/power/endergy/PowerConduitEndergy.java
It doesn't break current saves completely (just doesn't load correctly - when loading with this fix, every coduit has its subtype as before) but I missed a overwrite for `readFromNBT` to get the subtype also in our child class. I now moved the subtype completely to super class that we don't need to store the subtype twice.
Also I moved the code from `initIcons` to a protected method as suggested by @OneEyeMaker.
=> Minor hotfix + more cleanup for PowerConduitEndergy

src/main/java/crazypants/enderio/config/Config.java, src/main/java/crazypants/enderio/item/ItemMagnet.java, src/main/java/crazypants/enderio/item/darksteel/PoweredItemRenderer.java, src/main/java/crazypants/enderio/machine/capbank/BlockItemCapBank.java, src/main/java/crazypants/enderio/teleport/ItemTravelStaff.java
Same implementation/reason as https://github.com/GTNewHorizons/GT5-Unofficial/pull/2041
Added configs (personal section, both default to true)
Default:
No Durability Bar (caps, magnets, etc use minecraft `itemDamage` and will be handled in https://github.com/GTNewHorizons/DuraDisplay):
No Charge Bar (notice the black background is also adjusted):
Both Off:
=> Implement item bar visibility config

src/main/java/crazypants/enderio/conduit/AbstractConduit.java, src/main/java/crazypants/enderio/conduit/item/ItemConduit.java, src/main/java/crazypants/enderio/conduit/liquid/AbstractLiquidConduit.java
By changing the default connection mode in `AbstractConduit` in my other PR https://github.com/GTNewHorizons/EnderIO/pull/134, it affected all the conduits.
This PR reverts the previous change, and changes the default only for fluid conduits
btw this is a great example of why we shouldn't squash all PR, because when you try to look at the changes made in https://github.com/GTNewHorizons/EnderIO/pull/134 from the git log, it now shows 40 files changed when in reality only 6 lines were changed, the rest of the stuff in spotless
=> Set fluid conduit default connection mode to output only

src/main/java/crazypants/enderio/machine/obelisk/ObeliskSpecialRenderer.java, src/main/java/crazypants/enderio/waila/WailaCompat.java
Fixes two instances that leak the world on the client.
This one leaks the world by keeping an `EntityItem` instance alive that has a reference to the world [here](https://github.com/Minecraft-TA/EnderIO/blob/2470e81f0ef0e63405f494a165fd9aad3a13d85c/src/main/java/crazypants/enderio/machine/obelisk/ObeliskSpecialRenderer.java#L98). The fix just passes null to the `EntityItem` as its only used to render the item above the obelisks and it works fine without a world instance.
The second leak is storing an unnecessary instance of `IWailaDataAccessor` that stores the current world. The fix here is just to delete the field as it has no real usages and pass it as a parameter.
=> Clientside world leak

build.gradle, dependencies.gradle, src/main/java/crazypants/enderio/machine/AbstractMachineEntity.java, src/main/java/crazypants/enderio/machine/tank/BlockItemTank.java
A demonstration of the bug is available on YouTube [here](https://youtu.be/IOl1y-1E8TY)
In essence, when attempting to fill a tank that has been freshly crafted and otherwise contains no NBT data the apparent creation of a new SuperTank object is instead using the same SuperTank object over and over and thereby filling the tank with more water than should be possible. It's likely that the `static final` dummy object was intended to be a constant but Java's final keyword does not prevent the associated object's fields from being updated.
=> Fix an edge case pertaining to freshly crafted tanks

src/main/java/crazypants/enderio/config/Config.java, src/main/java/crazypants/enderio/teleport/TravelController.java
Config obviously defaults to making it continue validating as is, but allows the Staff Of Traveling keybind mod to continue working without any substantial code changes and/or having to have a server-side component coded in that mod.
Did it this way simply because it was the easiest way all around to continue having a keybind to use the staff of traveling. 
EDIT: Oh yea, and for reference, the mod (functionality) I'm wanting to have back: https://github.com/TheUnderTaker11/Staff-Of-Traveling-Keybind/tree/1.7.10
Not having to have it in your hand is SUPER nice, can't live without it now.
=> Add Config to allow servers to re-enable support for client-side 'hacks' like Staff Of Traveling Keybind mod.

src/main/java/crazypants/enderio/config/Config.java, src/main/java/crazypants/enderio/config/PacketConfigSync.java, src/main/java/crazypants/enderio/item/ItemMagnet.java, src/main/java/crazypants/enderio/item/KeyTracker.java, src/main/java/crazypants/enderio/teleport/ItemTeleportStaff.java, src/main/java/crazypants/enderio/teleport/ItemTravelStaff.java, src/main/java/crazypants/enderio/teleport/TravelController.java, src/main/java/crazypants/enderio/teleport/packet/PacketTravelEvent.java, src/main/resources/assets/enderio/lang/en_US.lang
Two main things
1. Added a keybind for Staff of Traveling blink ability
2. Due to the new keybind, also added Baubles support for Staff of Traveling.
By extension, both features 1 and 2 also apply to the Staff of Teleportation.
Further notes:
I have modified the "boolean isActive(EntityPlayer ep, ItemStack equipped)" on ItemTravelStaff and ItemTeleportStaff to just be true as long as the 'equipped' stack passed in isn't null. This isActive seems to me to lean more towards supporting enable/disabling items. It made no sense to me to have all this logic around if the player is holding the travel item, just to ask again, by passing in _the exact same item it pulled from player.getHeldItem()_. If I misunderstood something in reading the code let me know, otherwise I don't think my change to …
=> Staff Of Traveling Keybind Feature

src/main/java/crazypants/enderio/api/teleport/TravelSource.java, src/main/java/crazypants/enderio/teleport/TravelController.java, src/main/java/crazypants/enderio/teleport/anchor/TravelEntitySpecialRenderer.java
Also stop inventory scanning from happening every client tick, whoops. Tested by placing a debug point on line 768 of TravelController (in getRequiredPower) and a debug point at line 656 of TravelController (in findTravelItemInInventoryOrBaubles). Debug points were used to verify that the code was ONLY hit when actual teleport happens, and not happening every tick like what was accidentally happening before.
Did retroactive testing on basic keybind functionality, held staff functionality, and anchor functionality to double-check this didn't break anything.
=> Fix Anchor always rendering bug

src/main/java/crazypants/enderio/teleport/TravelController.java
Travel anchors' protection mode basically works, but you are not able to teleport to another travel anchor, even if you are authorized.
It looks looks like the server never knows which player is authorized. Only the current client knows it. Removing the check for authorization will bring back the intended behavior.
There [were a PR](https://github.com/GTNewHorizons/EnderIO/pull/128) in the past that added that method. Probably the behavior of the authorization was not clear there.
=> Fix protection mode of travel anchor

src/main/java/crazypants/enderio/waila/WailaCompat.java
The WAILA integration for the Dark Steel Anvil didn't work if the "Sneaky Facades" option was on (which it is by default). The integration fixes the metadata used to display the block. With "Sneaky Facades" on, if you were looking at undamaged Dark Steel Anvils facing certain directions, they would display as Slightly Damaged or Very Damaged. Slightly Damaged and Very Damaged would always display as undamaged. 
It was like this:
```java
if (config("Sneaky Facades"))
{
if (block instanceof Facade)
{
...
}
}
else if (block instanceof Dark Steel Anvil)
{
...
}
```
When it should be like this:
```java
if (config("Sneaky Facades") && block instanceof Facade)
{
...
}
else if (block instanceof Dark Steel Anvil)
{
...
}
```
=> Fix Dark Steel Anvils in WAILA

src/main/java/crazypants/enderio/conduit/AbstractItemConduit.java, src/main/java/crazypants/enderio/conduit/IConduitBundle.java, src/main/java/crazypants/enderio/conduit/TileConduitBundle.java
Replacing conduits erases connection data, meaning conduit networks need to be reconfigured. Especially inconvenient with fluid conduits.
Replacing conduits retains connection data including I/O state, filters, channels, and RR state. Very easy to upgrade to more powerful fluid and energy conduits.
=> Conduit Replacement Retains Connection Data

src/main/java/crazypants/enderio/machine/farm/FarmingStationRenderer.java
This PR replaces the squished portal texture on the active FarmingStation with a properly sized crop of that texture. The animation is still the exact same thus requiring no changes to resource packs.
=> Improve FarmingStation portal texture rendering

src/main/java/crazypants/enderio/config/Config.java, src/main/java/crazypants/enderio/machine/farm/PacketFarmAction.java, src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java, src/main/java/crazypants/util/ClientUtil.java
Nobody cares about these particles. But it can be pretty laggy with fast/large tree farms.
* decrease number of Farming Station particles (scaled with client setting)
* decrease range of Farming Station particles
* add max range of Farming Station particles to config
=> Add config entries for Farming Station particles

src/main/java/crazypants/enderio/conduit/liquid/LiquidConduitRenderer.java
Fixes a data race via proper locking in the SynchronizedMap by using `computeIfAbsent` instead.  The prior method could create `cache0` twice in different threads, they each hold their own instance while only one gets stored in the map, they each add data to it, then one gets GC'd.
=> Fix another thread data race issue introduced in #164.

src/main/java/crazypants/enderio/teleport/TravelController.java
Due to https://github.com/GTNewHorizons/EnderIO/pull/168, GTNH Lib is now a hard-dep. This makes the `Loader.isModLoaded()`-check obsolete.
=> Remove `isModLoaded` check for GTNH Lib

src/main/java/crazypants/enderio/item/KeyTracker.java, src/main/java/crazypants/enderio/item/darksteel/ItemDarkSteelSword.java, src/main/java/crazypants/enderio/teleport/ItemTeleportStaff.java, src/main/java/crazypants/enderio/teleport/TravelController.java
Fixes 2 separate bugs with the SoT keybind.
1. Staff of Teleportation in GTNH pack specifically didn't work due to reporting as having 0 power through the RF API. 
- Fixed this by having it always report that it's full of power since it has infinite/doesn't use power.
2. BlackSteelSword and EndSteelSword (The Ender and MKII) both were quite funky with keybind, causing no teleports to happen when they really should have. 
- Fixed this through tweaks to how this is handled in a number of places to allow for proper handling while not changing the default held/shift held behavior.
Tested in SP, Anchor behavior while holding staffs and Swords with travel upgrade on them work as expected. Keybind now works and is able to use swords with travel upgrade on them. 
One quirk is that if you are …
=> Travel Staff Blink Keybind fixes.

src/main/java/crazypants/enderio/material/Alloy.java
It was mistakenly adding two oredicts. upstream changed this 8 years ago in some refactors. This double oredict served no purpose and is causing severe compatability issues (e.g. with GT).
related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17538
=> fix broken oredicts for vibrantalloy and pulsatingIron

src/main/java/crazypants/enderio/ClientProxy.java, src/main/java/crazypants/enderio/conduit/liquid/LiquidConduitRenderer.java, src/main/java/crazypants/enderio/conduit/render/ConduitBundleRenderer.java, src/main/java/crazypants/enderio/conduit/render/ConduitRenderer.java, src/main/java/crazypants/enderio/conduit/render/DefaultConduitRenderer.java
This change completely removes the TESR for all conduits. The TESR was only actually used by the basic fluid conduit to render the fluid texture inside the conduit, this is mostly entirely unnecessary and can be rendered via the ISBRH.
All conduits other than the basic fluid conduit are completely unchanged by this, and as of writing there is a minor change to the rendering of the basic fluid conduit. The first image below is the original rendering with the TESR, the second image is the new rendering from ISBRH. The only different is that I'm not sure how to make it not darken the top(I also can't tell how the TESR is doing this either).
The advantage of this change is that currently the TESR, while largely unused, is still implemented for every single conduit, meaning that the rendering …
=> No more TESR on conduits

src/main/resources/assets/enderio/lang/en_US.lang
This adds some missing localizations for unlocalized names returned by the ItemStack-insensitive version of `Item.getUnlocalizedName()`.
Relevant for the Item/Block stats introduced in https://github.com/GTNewHorizons/Hodgepodge/pull/398.
=> Add Localizations

src/main/java/crazypants/enderio/item/darksteel/ItemDarkSteelArmor.java
The naturalist's eyes upgrade for the dark helm had a flipped bool condition and didn't work.
Fixed it
=> Fix naturalist's eyes

src/main/java/crazypants/enderio/EnderIO.java, src/main/java/crazypants/enderio/item/darksteel/ItemEndSteelArmor.java, src/main/java/crazypants/enderio/item/darksteel/ItemStellarArmor.java
If standalone gt5 also uses this api then the compat will have to change back to a check for gregtech but only if gregapi isn't loaded, not sure if its possible on the optional decorator
=> Change hazmat Optional decorators' modid from `gregtech` to `gregtech_nh` to add gt6 compat

src/main/java/crazypants/enderio/machine/capbank/BlockCapBank.java, src/main/java/crazypants/enderio/machine/capbank/TileCapBank.java, src/main/java/crazypants/enderio/machine/power/BlockCapacitorBank.java, src/main/java/crazypants/enderio/machine/power/TileCapacitorBank.java, src/main/java/crazypants/enderio/machine/tank/BlockTank.java, src/main/java/crazypants/enderio/machine/tank/TileTank.java, src/main/java/crazypants/enderio/machine/vacuum/TileVacuumChest.java
Closes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19692
This PR adds comparator logic to the Vacuum chest, but more importantly completes an already half-done effort to move all base comparator impl to BlockEnder, and then hold the actual functions for comparator output strength in the TileEntity as an implementation of IComparatorOutput.
=> Comparator refactor and Vacuum Chest logic
